# Generated by Django 3.1.2 on 2020-11-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customer_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='subcategory',
            new_name='brand',
        ),
    ]
