# Generated by Django 3.1.2 on 2020-11-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20201128_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_category',
            field=models.CharField(default='', max_length=50),
        ),
    ]
