# Generated by Django 3.1.2 on 2020-11-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_category_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sub_category',
        ),
    ]
