# Generated by Django 3.1.2 on 2020-12-03 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201203_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publish_date',
        ),
    ]
