# Generated by Django 3.1.2 on 2020-12-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_auto_20201209_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_img1',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_img2',
            field=models.ImageField(default='', upload_to='shop/images'),
        ),
    ]
